Rmove InPullConnector class
open-rsx/rsb-spread-cpp pull request #7
Opened 2018-11-08 15:20 UTC by scymtym

This supersedes and extends #5.

Will fix #2.

2018-11-08 18:11 UTC, scymtym commented
Now with mock-based for connector deactivation. Should be ready.

2018-11-09 09:11 UTC, languitar requested changes
Just a few minor things.

2018-11-09 09:11 UTC, languitar commented on test/rsb/transport/ConnectorTest.cpp
> +    MOCK_METHOD2(addSink, void(const rsb::Scope& scope, rsb::transport::spread::Bus::SinkPtr sink));
Didn't we have something like an 80 characters line length restriction usually?

2018-11-09 09:11 UTC, languitar commented on test/rsb/transport/ConnectorTest.h
> +    boost::function<rsb::transport::InConnectorPtr()> createConnectingInConnector;
Maybe some comments here to describe what the new functions are and how they differ from the renamed existing ones?

2018-11-09 18:03 UTC, scymtym commented on test/rsb/transport/ConnectorTest.cpp
> +    MOCK_METHOD2(addSink, void(const rsb::Scope& scope, rsb::transport::spread::Bus::SinkPtr sink));
Mostly addressed.

2018-11-09 18:03 UTC, scymtym commented on test/rsb/transport/ConnectorTest.h
> +    boost::function<rsb::transport::InConnectorPtr()> createConnectingInConnector;
Done.

2018-11-12 10:33 UTC, languitar approved these changes

2018-11-12 10:34 UTC, merged